name: cv_application
description: 👤simple portfolio project with Flutter.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^9.2.0

 
flutter:
  assets:
    - images/Bardia.png
    - images/Android.png
    - images/Dart.png
    - images/Flutter.png
    - images/Ios.png

  fonts:
    - family: vazir
      fonts:
        - asset: fonts/vazir_fd_medium_wol.ttf
 
